# Generated by Django 3.2.10 on 2022-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
