from django.db import models

# Create your models here.
class apis(models.Model):
    id = models.AutoField(primary_key=True)
    apiId = models.CharField(max_length=500)
    title = models.CharField(max_length=500)
    summary = models.CharField(max_length=500)
    rating = models.FloatField(null=True,blank=True, default=None)
    name = models.CharField(max_length=500)
    label=models.CharField(max_length=500)
    author=models.CharField(max_length=500)
    description=models.CharField(max_length=500)
    type=models.CharField(max_length=500)
    downloads=models.CharField(max_length=500)
    useCount=models.CharField(max_length=500)
    sampleUrl=models.CharField(max_length=500)
    downloadUrl=models.CharField(max_length=500)
    dateModified=models.CharField(max_length=500)
    remoteFeed=models.CharField(max_length=500)
    numComments=models.CharField(max_length=500)
    commentsUrl=models.CharField(max_length=500)
    Tags=models.CharField(max_length=500)
    category=models.CharField(max_length=500)
    protocols=models.CharField(max_length=500)
    serviceEndpoint=models.CharField(max_length=500)
    version=models.CharField(max_length=500)
    wsdl=models.CharField(max_length=500)
    data_formats=models.CharField(max_length=500)
    apigroups=models.CharField(max_length=500)
    example=models.CharField(max_length=500)
    clientInstall=models.CharField(max_length=500)
    authentication=models.CharField(max_length=500)
    ssl=models.CharField(max_length=500)
    readonly=models.CharField(max_length=500)
    VendorApiKits=models.CharField(max_length=500)
    CommunityApiKits=models.CharField(max_length=500)
    blog=models.CharField(max_length=500)
    forum=models.CharField(max_length=500)
    support=models.CharField(max_length=500)
    accountReq=models.CharField(max_length=500) 
    commercial=models.CharField(max_length=500) 
    provider=models.CharField(max_length=500)
    managedBy=models.CharField(max_length=500)
    nonCommercial=models.CharField(max_length=500)
    dataLicensing=models.CharField(max_length=500)
    fees=models.CharField(max_length=500)
    limits=models.CharField(max_length=500)
    terms=models.CharField(max_length=500)
    company=models.CharField(max_length=500)
    updated=models.CharField(max_length=500)
    

class mashs(models.Model):
    id = models.AutoField(primary_key=True)
    apiId = models.CharField(max_length=500)
    title= models.CharField(max_length=500)
    summary= models.CharField(max_length=500)
    rating = models.FloatField(null=True,blank=True, default=None)
    name= models.CharField(max_length=500)
    label= models.CharField(max_length=500)
    author= models.CharField(max_length=500)
    description= models.CharField(max_length=500)
    type= models.CharField(max_length=500)
    downloads= models.CharField(max_length=500)
    useCount= models.CharField(max_length=500)
    sampleUrl= models.CharField(max_length=500)
    dateModified= models.CharField(max_length=500)
    numComments= models.CharField(max_length=500)
    commentsUrl= models.CharField(max_length=500)
    Tags= models.CharField(max_length=500)
    APIs= models.CharField(max_length=500)
    updated= models.CharField(max_length=500)
